### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.Application.Core.ICommand`1
  commentId: T:AdvanceFileUpload.Application.Core.ICommand`1
  id: ICommand`1
  parent: AdvanceFileUpload.Application.Core
  children: []
  langs:
  - csharp
  - vb
  name: ICommand<TResult>
  nameWithType: ICommand<TResult>
  fullName: AdvanceFileUpload.Application.Core.ICommand<TResult>
  type: Interface
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application/Core/ICommand.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: ICommand
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application/Core/ICommand.cs
    startLine: 9
  assemblies:
  - AdvanceFileUpload.Application
  namespace: AdvanceFileUpload.Application.Core
  syntax:
    content: 'public interface ICommand<out TResult> : IRequest<TResult>, IBaseRequest'
    typeParameters:
    - id: TResult
    content.vb: Public Interface ICommand(Of Out TResult) Inherits IRequest(Of TResult), IBaseRequest
  nameWithType.vb: ICommand(Of TResult)
  fullName.vb: AdvanceFileUpload.Application.Core.ICommand(Of TResult)
  name.vb: ICommand(Of TResult)
references:
- uid: AdvanceFileUpload.Application.Core
  commentId: N:AdvanceFileUpload.Application.Core
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.Application.Core
  nameWithType: AdvanceFileUpload.Application.Core
  fullName: AdvanceFileUpload.Application.Core
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Core
    name: Core
    href: AdvanceFileUpload.Application.Core.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Core
    name: Core
    href: AdvanceFileUpload.Application.Core.html
