### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.Application.Shared.UploadStatus
  commentId: T:AdvanceFileUpload.Application.Shared.UploadStatus
  id: UploadStatus
  parent: AdvanceFileUpload.Application.Shared
  children:
  - AdvanceFileUpload.Application.Shared.UploadStatus.Completed
  - AdvanceFileUpload.Application.Shared.UploadStatus.Failed
  - AdvanceFileUpload.Application.Shared.UploadStatus.InProgress
  - AdvanceFileUpload.Application.Shared.UploadStatus.Pending
  langs:
  - csharp
  - vb
  name: UploadStatus
  nameWithType: UploadStatus
  fullName: AdvanceFileUpload.Application.Shared.UploadStatus
  type: Enum
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: UploadStatus
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
    startLine: 147
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Represents the status of an upload session.
  example: []
  syntax:
    content: public enum UploadStatus
    content.vb: Public Enum UploadStatus
- uid: AdvanceFileUpload.Application.Shared.UploadStatus.Pending
  commentId: F:AdvanceFileUpload.Application.Shared.UploadStatus.Pending
  id: Pending
  parent: AdvanceFileUpload.Application.Shared.UploadStatus
  langs:
  - csharp
  - vb
  name: Pending
  nameWithType: UploadStatus.Pending
  fullName: AdvanceFileUpload.Application.Shared.UploadStatus.Pending
  type: Field
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: Pending
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
    startLine: 152
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: The upload session is pending.
  example: []
  syntax:
    content: Pending = 0
    return:
      type: AdvanceFileUpload.Application.Shared.UploadStatus
- uid: AdvanceFileUpload.Application.Shared.UploadStatus.InProgress
  commentId: F:AdvanceFileUpload.Application.Shared.UploadStatus.InProgress
  id: InProgress
  parent: AdvanceFileUpload.Application.Shared.UploadStatus
  langs:
  - csharp
  - vb
  name: InProgress
  nameWithType: UploadStatus.InProgress
  fullName: AdvanceFileUpload.Application.Shared.UploadStatus.InProgress
  type: Field
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: InProgress
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
    startLine: 157
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: The upload session is in progress.
  example: []
  syntax:
    content: InProgress = 1
    return:
      type: AdvanceFileUpload.Application.Shared.UploadStatus
- uid: AdvanceFileUpload.Application.Shared.UploadStatus.Completed
  commentId: F:AdvanceFileUpload.Application.Shared.UploadStatus.Completed
  id: Completed
  parent: AdvanceFileUpload.Application.Shared.UploadStatus
  langs:
  - csharp
  - vb
  name: Completed
  nameWithType: UploadStatus.Completed
  fullName: AdvanceFileUpload.Application.Shared.UploadStatus.Completed
  type: Field
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: Completed
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
    startLine: 162
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: The upload session is completed.
  example: []
  syntax:
    content: Completed = 2
    return:
      type: AdvanceFileUpload.Application.Shared.UploadStatus
- uid: AdvanceFileUpload.Application.Shared.UploadStatus.Failed
  commentId: F:AdvanceFileUpload.Application.Shared.UploadStatus.Failed
  id: Failed
  parent: AdvanceFileUpload.Application.Shared.UploadStatus
  langs:
  - csharp
  - vb
  name: Failed
  nameWithType: UploadStatus.Failed
  fullName: AdvanceFileUpload.Application.Shared.UploadStatus.Failed
  type: Field
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: Failed
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/CreateUploadSession.cs
    startLine: 167
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: The upload session has failed.
  example: []
  syntax:
    content: Failed = 3
    return:
      type: AdvanceFileUpload.Application.Shared.UploadStatus
references:
- uid: AdvanceFileUpload.Application.Shared
  commentId: N:AdvanceFileUpload.Application.Shared
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.Application.Shared
  nameWithType: AdvanceFileUpload.Application.Shared
  fullName: AdvanceFileUpload.Application.Shared
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Shared
    name: Shared
    href: AdvanceFileUpload.Application.Shared.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Shared
    name: Shared
    href: AdvanceFileUpload.Application.Shared.html
- uid: AdvanceFileUpload.Application.Shared.UploadStatus
  commentId: T:AdvanceFileUpload.Application.Shared.UploadStatus
  parent: AdvanceFileUpload.Application.Shared
  href: AdvanceFileUpload.Application.Shared.UploadStatus.html
  name: UploadStatus
  nameWithType: UploadStatus
  fullName: AdvanceFileUpload.Application.Shared.UploadStatus
