### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.Application.Shared.IChunkValidator
  commentId: T:AdvanceFileUpload.Application.Shared.IChunkValidator
  id: IChunkValidator
  parent: AdvanceFileUpload.Application.Shared
  children:
  - AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData(System.Byte[],System.Int64)
  - AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex(System.Int32)
  - AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize(System.Int64,System.Int64)
  langs:
  - csharp
  - vb
  name: IChunkValidator
  nameWithType: IChunkValidator
  fullName: AdvanceFileUpload.Application.Shared.IChunkValidator
  type: Interface
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IChunkValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IChunkValidator
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IChunkValidator.cs
    startLine: 6
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Interface for validating file chunks.
  example: []
  syntax:
    content: public interface IChunkValidator
    content.vb: Public Interface IChunkValidator
- uid: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex(System.Int32)
  commentId: M:AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex(System.Int32)
  id: ValidateChunkIndex(System.Int32)
  parent: AdvanceFileUpload.Application.Shared.IChunkValidator
  langs:
  - csharp
  - vb
  name: ValidateChunkIndex(int)
  nameWithType: IChunkValidator.ValidateChunkIndex(int)
  fullName: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex(int)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IChunkValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: ValidateChunkIndex
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IChunkValidator.cs
    startLine: 13
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Validates the chunk index.
  example: []
  syntax:
    content: bool ValidateChunkIndex(int chunkIndex)
    parameters:
    - id: chunkIndex
      type: System.Int32
      description: The index of the chunk to validate.
    return:
      type: System.Boolean
      description: True if the chunk index is valid; otherwise, false.
    content.vb: Function ValidateChunkIndex(chunkIndex As Integer) As Boolean
  overload: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex*
  nameWithType.vb: IChunkValidator.ValidateChunkIndex(Integer)
  fullName.vb: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex(Integer)
  name.vb: ValidateChunkIndex(Integer)
- uid: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData(System.Byte[],System.Int64)
  commentId: M:AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData(System.Byte[],System.Int64)
  id: ValidateChunkData(System.Byte[],System.Int64)
  parent: AdvanceFileUpload.Application.Shared.IChunkValidator
  langs:
  - csharp
  - vb
  name: ValidateChunkData(byte[], long)
  nameWithType: IChunkValidator.ValidateChunkData(byte[], long)
  fullName: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData(byte[], long)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IChunkValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: ValidateChunkData
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IChunkValidator.cs
    startLine: 21
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Validates the chunk data.
  example: []
  syntax:
    content: bool ValidateChunkData(byte[] chunkData, long MaxChunkSize)
    parameters:
    - id: chunkData
      type: System.Byte[]
      description: The data of the chunk to validate.
    - id: MaxChunkSize
      type: System.Int64
      description: The maximum size of the chunk.
    return:
      type: System.Boolean
      description: True if the chunk data is valid; otherwise, false.
    content.vb: Function ValidateChunkData(chunkData As Byte(), MaxChunkSize As Long) As Boolean
  overload: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData*
  nameWithType.vb: IChunkValidator.ValidateChunkData(Byte(), Long)
  fullName.vb: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData(Byte(), Long)
  name.vb: ValidateChunkData(Byte(), Long)
- uid: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize(System.Int64,System.Int64)
  commentId: M:AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize(System.Int64,System.Int64)
  id: ValidateChunkSize(System.Int64,System.Int64)
  parent: AdvanceFileUpload.Application.Shared.IChunkValidator
  langs:
  - csharp
  - vb
  name: ValidateChunkSize(long, long)
  nameWithType: IChunkValidator.ValidateChunkSize(long, long)
  fullName: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize(long, long)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IChunkValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: ValidateChunkSize
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IChunkValidator.cs
    startLine: 32
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Validates the size of the chunk.
  example: []
  syntax:
    content: bool ValidateChunkSize(long chunkSize, long maxChunkSize)
    parameters:
    - id: chunkSize
      type: System.Int64
      description: The size of the chunk to validate.
    - id: maxChunkSize
      type: System.Int64
      description: The maximum allowed size of the chunk.
    return:
      type: System.Boolean
      description: True if the chunk size is valid; otherwise, false.
    content.vb: Function ValidateChunkSize(chunkSize As Long, maxChunkSize As Long) As Boolean
  overload: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize*
  nameWithType.vb: IChunkValidator.ValidateChunkSize(Long, Long)
  fullName.vb: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize(Long, Long)
  name.vb: ValidateChunkSize(Long, Long)
references:
- uid: AdvanceFileUpload.Application.Shared
  commentId: N:AdvanceFileUpload.Application.Shared
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.Application.Shared
  nameWithType: AdvanceFileUpload.Application.Shared
  fullName: AdvanceFileUpload.Application.Shared
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Shared
    name: Shared
    href: AdvanceFileUpload.Application.Shared.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Shared
    name: Shared
    href: AdvanceFileUpload.Application.Shared.html
- uid: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex*
  commentId: Overload:AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex
  href: AdvanceFileUpload.Application.Shared.IChunkValidator.html#AdvanceFileUpload_Application_Shared_IChunkValidator_ValidateChunkIndex_System_Int32_
  name: ValidateChunkIndex
  nameWithType: IChunkValidator.ValidateChunkIndex
  fullName: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkIndex
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData*
  commentId: Overload:AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData
  href: AdvanceFileUpload.Application.Shared.IChunkValidator.html#AdvanceFileUpload_Application_Shared_IChunkValidator_ValidateChunkData_System_Byte___System_Int64_
  name: ValidateChunkData
  nameWithType: IChunkValidator.ValidateChunkData
  fullName: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkData
- uid: System.Byte[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte[]
  nameWithType: byte[]
  fullName: byte[]
  nameWithType.vb: Byte()
  fullName.vb: Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: (
  - name: )
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize*
  commentId: Overload:AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize
  href: AdvanceFileUpload.Application.Shared.IChunkValidator.html#AdvanceFileUpload_Application_Shared_IChunkValidator_ValidateChunkSize_System_Int64_System_Int64_
  name: ValidateChunkSize
  nameWithType: IChunkValidator.ValidateChunkSize
  fullName: AdvanceFileUpload.Application.Shared.IChunkValidator.ValidateChunkSize
