### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.API.CertificateSettings
  commentId: T:AdvanceFileUpload.API.CertificateSettings
  id: CertificateSettings
  parent: AdvanceFileUpload.API
  children:
  - AdvanceFileUpload.API.CertificateSettings.Location
  - AdvanceFileUpload.API.CertificateSettings.Password
  - AdvanceFileUpload.API.CertificateSettings.Path
  - AdvanceFileUpload.API.CertificateSettings.Store
  - AdvanceFileUpload.API.CertificateSettings.Subject
  langs:
  - csharp
  - vb
  name: CertificateSettings
  nameWithType: CertificateSettings
  fullName: AdvanceFileUpload.API.CertificateSettings
  type: Class
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: CertificateSettings
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
    startLine: 90
  assemblies:
  - AdvanceFileUpload.API
  namespace: AdvanceFileUpload.API
  summary: >-
    Represents the certificate configuration options for HTTPS endpoints.

    Provides information for locating and authenticating the certificate.
  example: []
  syntax:
    content: public class CertificateSettings
    content.vb: Public Class CertificateSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: AdvanceFileUpload.API.CertificateSettings.Path
  commentId: P:AdvanceFileUpload.API.CertificateSettings.Path
  id: Path
  parent: AdvanceFileUpload.API.CertificateSettings
  langs:
  - csharp
  - vb
  name: Path
  nameWithType: CertificateSettings.Path
  fullName: AdvanceFileUpload.API.CertificateSettings.Path
  type: Property
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: Path
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
    startLine: 95
  assemblies:
  - AdvanceFileUpload.API
  namespace: AdvanceFileUpload.API
  summary: Gets or sets the file path to the certificate (PFX or P12 format).
  example: []
  syntax:
    content: public string Path { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Path As String
  overload: AdvanceFileUpload.API.CertificateSettings.Path*
- uid: AdvanceFileUpload.API.CertificateSettings.Password
  commentId: P:AdvanceFileUpload.API.CertificateSettings.Password
  id: Password
  parent: AdvanceFileUpload.API.CertificateSettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: CertificateSettings.Password
  fullName: AdvanceFileUpload.API.CertificateSettings.Password
  type: Property
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: Password
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
    startLine: 101
  assemblies:
  - AdvanceFileUpload.API
  namespace: AdvanceFileUpload.API
  summary: >-
    Gets or sets the certificate password.

    It is recommended to use environment variables or secure stores for production.
  example: []
  syntax:
    content: public string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: AdvanceFileUpload.API.CertificateSettings.Password*
- uid: AdvanceFileUpload.API.CertificateSettings.Store
  commentId: P:AdvanceFileUpload.API.CertificateSettings.Store
  id: Store
  parent: AdvanceFileUpload.API.CertificateSettings
  langs:
  - csharp
  - vb
  name: Store
  nameWithType: CertificateSettings.Store
  fullName: AdvanceFileUpload.API.CertificateSettings.Store
  type: Property
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: Store
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
    startLine: 106
  assemblies:
  - AdvanceFileUpload.API
  namespace: AdvanceFileUpload.API
  summary: Gets or sets the name of the Windows certificate store (e.g., "My", "Root").
  example: []
  syntax:
    content: public string Store { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Store As String
  overload: AdvanceFileUpload.API.CertificateSettings.Store*
- uid: AdvanceFileUpload.API.CertificateSettings.Location
  commentId: P:AdvanceFileUpload.API.CertificateSettings.Location
  id: Location
  parent: AdvanceFileUpload.API.CertificateSettings
  langs:
  - csharp
  - vb
  name: Location
  nameWithType: CertificateSettings.Location
  fullName: AdvanceFileUpload.API.CertificateSettings.Location
  type: Property
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: Location
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
    startLine: 111
  assemblies:
  - AdvanceFileUpload.API
  namespace: AdvanceFileUpload.API
  summary: Gets or sets the certificate store location, such as "LocalMachine" or "CurrentUser".
  example: []
  syntax:
    content: public string Location { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Location As String
  overload: AdvanceFileUpload.API.CertificateSettings.Location*
- uid: AdvanceFileUpload.API.CertificateSettings.Subject
  commentId: P:AdvanceFileUpload.API.CertificateSettings.Subject
  id: Subject
  parent: AdvanceFileUpload.API.CertificateSettings
  langs:
  - csharp
  - vb
  name: Subject
  nameWithType: CertificateSettings.Subject
  fullName: AdvanceFileUpload.API.CertificateSettings.Subject
  type: Property
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: Subject
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.API/ServiceConfiguration/KestrelConfiguration.cs
    startLine: 116
  assemblies:
  - AdvanceFileUpload.API
  namespace: AdvanceFileUpload.API
  summary: Gets or sets the subject name for certificate lookup in the store.
  example: []
  syntax:
    content: public string Subject { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Subject As String
  overload: AdvanceFileUpload.API.CertificateSettings.Subject*
references:
- uid: AdvanceFileUpload.API
  commentId: N:AdvanceFileUpload.API
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.API
  nameWithType: AdvanceFileUpload.API
  fullName: AdvanceFileUpload.API
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.API
    name: API
    href: AdvanceFileUpload.API.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.API
    name: API
    href: AdvanceFileUpload.API.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: AdvanceFileUpload.API.CertificateSettings.Path*
  commentId: Overload:AdvanceFileUpload.API.CertificateSettings.Path
  href: AdvanceFileUpload.API.CertificateSettings.html#AdvanceFileUpload_API_CertificateSettings_Path
  name: Path
  nameWithType: CertificateSettings.Path
  fullName: AdvanceFileUpload.API.CertificateSettings.Path
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: AdvanceFileUpload.API.CertificateSettings.Password*
  commentId: Overload:AdvanceFileUpload.API.CertificateSettings.Password
  href: AdvanceFileUpload.API.CertificateSettings.html#AdvanceFileUpload_API_CertificateSettings_Password
  name: Password
  nameWithType: CertificateSettings.Password
  fullName: AdvanceFileUpload.API.CertificateSettings.Password
- uid: AdvanceFileUpload.API.CertificateSettings.Store*
  commentId: Overload:AdvanceFileUpload.API.CertificateSettings.Store
  href: AdvanceFileUpload.API.CertificateSettings.html#AdvanceFileUpload_API_CertificateSettings_Store
  name: Store
  nameWithType: CertificateSettings.Store
  fullName: AdvanceFileUpload.API.CertificateSettings.Store
- uid: AdvanceFileUpload.API.CertificateSettings.Location*
  commentId: Overload:AdvanceFileUpload.API.CertificateSettings.Location
  href: AdvanceFileUpload.API.CertificateSettings.html#AdvanceFileUpload_API_CertificateSettings_Location
  name: Location
  nameWithType: CertificateSettings.Location
  fullName: AdvanceFileUpload.API.CertificateSettings.Location
- uid: AdvanceFileUpload.API.CertificateSettings.Subject*
  commentId: Overload:AdvanceFileUpload.API.CertificateSettings.Subject
  href: AdvanceFileUpload.API.CertificateSettings.html#AdvanceFileUpload_API_CertificateSettings_Subject
  name: Subject
  nameWithType: CertificateSettings.Subject
  fullName: AdvanceFileUpload.API.CertificateSettings.Subject
