### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.Application.Validators.FileCompressionValidator
  commentId: T:AdvanceFileUpload.Application.Validators.FileCompressionValidator
  id: FileCompressionValidator
  parent: AdvanceFileUpload.Application.Validators
  children:
  - AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  langs:
  - csharp
  - vb
  name: FileCompressionValidator
  nameWithType: FileCompressionValidator
  fullName: AdvanceFileUpload.Application.Validators.FileCompressionValidator
  type: Class
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/FileComressionValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: FileCompressionValidator
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/FileComressionValidator.cs
    startLine: 7
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Represents a File Compression validator.
  example: []
  syntax:
    content: 'public class FileCompressionValidator : IFileCompressionValidator'
    content.vb: Public Class FileCompressionValidator Implements IFileCompressionValidator
  inheritance:
  - System.Object
  implements:
  - AdvanceFileUpload.Application.Validators.IFileCompressionValidator
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  commentId: M:AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  id: IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  parent: AdvanceFileUpload.Application.Validators.FileCompressionValidator
  langs:
  - csharp
  - vb
  name: IsValidCompressedData(byte[], CompressionAlgorithmOption)
  nameWithType: FileCompressionValidator.IsValidCompressedData(byte[], CompressionAlgorithmOption)
  fullName: AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData(byte[], AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/FileComressionValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IsValidCompressedData
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/FileComressionValidator.cs
    startLine: 10
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Validates if the provided file data is correctly compressed using the specified compression algorithm.
  example: []
  syntax:
    content: public bool IsValidCompressedData(byte[] data, CompressionAlgorithmOption compressionAlgorithmOption)
    parameters:
    - id: data
      type: System.Byte[]
      description: The file data to validate.
    - id: compressionAlgorithmOption
      type: AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption
      description: The compression algorithm used to compress the data.
    return:
      type: System.Boolean
      description: True if the data is valid compressed data; otherwise, false.
    content.vb: Public Function IsValidCompressedData(data As Byte(), compressionAlgorithmOption As CompressionAlgorithmOption) As Boolean
  overload: AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData*
  implements:
  - AdvanceFileUpload.Application.Validators.IFileCompressionValidator.IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  nameWithType.vb: FileCompressionValidator.IsValidCompressedData(Byte(), CompressionAlgorithmOption)
  fullName.vb: AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData(Byte(), AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  name.vb: IsValidCompressedData(Byte(), CompressionAlgorithmOption)
references:
- uid: AdvanceFileUpload.Application.Validators
  commentId: N:AdvanceFileUpload.Application.Validators
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.Application.Validators
  nameWithType: AdvanceFileUpload.Application.Validators
  fullName: AdvanceFileUpload.Application.Validators
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Validators
    name: Validators
    href: AdvanceFileUpload.Application.Validators.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Validators
    name: Validators
    href: AdvanceFileUpload.Application.Validators.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: AdvanceFileUpload.Application.Validators.IFileCompressionValidator
  commentId: T:AdvanceFileUpload.Application.Validators.IFileCompressionValidator
  parent: AdvanceFileUpload.Application.Validators
  href: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.html
  name: IFileCompressionValidator
  nameWithType: IFileCompressionValidator
  fullName: AdvanceFileUpload.Application.Validators.IFileCompressionValidator
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData*
  commentId: Overload:AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData
  href: AdvanceFileUpload.Application.Validators.FileCompressionValidator.html#AdvanceFileUpload_Application_Validators_FileCompressionValidator_IsValidCompressedData_System_Byte___AdvanceFileUpload_Application_Compression_CompressionAlgorithmOption_
  name: IsValidCompressedData
  nameWithType: FileCompressionValidator.IsValidCompressedData
  fullName: AdvanceFileUpload.Application.Validators.FileCompressionValidator.IsValidCompressedData
- uid: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  commentId: M:AdvanceFileUpload.Application.Validators.IFileCompressionValidator.IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  parent: AdvanceFileUpload.Application.Validators.IFileCompressionValidator
  isExternal: true
  href: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.html#AdvanceFileUpload_Application_Validators_IFileCompressionValidator_IsValidCompressedData_System_Byte___AdvanceFileUpload_Application_Compression_CompressionAlgorithmOption_
  name: IsValidCompressedData(byte[], CompressionAlgorithmOption)
  nameWithType: IFileCompressionValidator.IsValidCompressedData(byte[], CompressionAlgorithmOption)
  fullName: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.IsValidCompressedData(byte[], AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  nameWithType.vb: IFileCompressionValidator.IsValidCompressedData(Byte(), CompressionAlgorithmOption)
  fullName.vb: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.IsValidCompressedData(Byte(), AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
  name.vb: IsValidCompressedData(Byte(), CompressionAlgorithmOption)
  spec.csharp:
  - uid: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
    name: IsValidCompressedData
    href: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.html#AdvanceFileUpload_Application_Validators_IFileCompressionValidator_IsValidCompressedData_System_Byte___AdvanceFileUpload_Application_Compression_CompressionAlgorithmOption_
  - name: (
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '['
  - name: ']'
  - name: ','
  - name: " "
  - uid: AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption
    name: CompressionAlgorithmOption
    href: AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption.html
  - name: )
  spec.vb:
  - uid: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.IsValidCompressedData(System.Byte[],AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption)
    name: IsValidCompressedData
    href: AdvanceFileUpload.Application.Validators.IFileCompressionValidator.html#AdvanceFileUpload_Application_Validators_IFileCompressionValidator_IsValidCompressedData_System_Byte___AdvanceFileUpload_Application_Compression_CompressionAlgorithmOption_
  - name: (
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: (
  - name: )
  - name: ','
  - name: " "
  - uid: AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption
    name: CompressionAlgorithmOption
    href: AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption.html
  - name: )
- uid: System.Byte[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte[]
  nameWithType: byte[]
  fullName: byte[]
  nameWithType.vb: Byte()
  fullName.vb: Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: (
  - name: )
- uid: AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption
  commentId: T:AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption
  parent: AdvanceFileUpload.Application.Compression
  href: AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption.html
  name: CompressionAlgorithmOption
  nameWithType: CompressionAlgorithmOption
  fullName: AdvanceFileUpload.Application.Compression.CompressionAlgorithmOption
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: AdvanceFileUpload.Application.Compression
  commentId: N:AdvanceFileUpload.Application.Compression
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.Application.Compression
  nameWithType: AdvanceFileUpload.Application.Compression
  fullName: AdvanceFileUpload.Application.Compression
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Compression
    name: Compression
    href: AdvanceFileUpload.Application.Compression.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Compression
    name: Compression
    href: AdvanceFileUpload.Application.Compression.html
