### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.Application.Validators.IFileValidator
  commentId: T:AdvanceFileUpload.Application.Validators.IFileValidator
  id: IFileValidator
  parent: AdvanceFileUpload.Application.Validators
  children:
  - AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension(System.String,System.String[])
  - AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName(System.String)
  - AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize(System.Int64,System.Int64)
  langs:
  - csharp
  - vb
  name: IFileValidator
  nameWithType: IFileValidator
  fullName: AdvanceFileUpload.Application.Validators.IFileValidator
  type: Interface
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IFileValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IFileValidator
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IFileValidator.cs
    startLine: 6
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Interface for validating files.
  example: []
  syntax:
    content: public interface IFileValidator
    content.vb: Public Interface IFileValidator
- uid: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName(System.String)
  commentId: M:AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName(System.String)
  id: IsValidFileName(System.String)
  parent: AdvanceFileUpload.Application.Validators.IFileValidator
  langs:
  - csharp
  - vb
  name: IsValidFileName(string)
  nameWithType: IFileValidator.IsValidFileName(string)
  fullName: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName(string)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IFileValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IsValidFileName
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IFileValidator.cs
    startLine: 13
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Validates the file name.
  example: []
  syntax:
    content: bool IsValidFileName(string fileName)
    parameters:
    - id: fileName
      type: System.String
      description: The name of the file to validate.
    return:
      type: System.Boolean
      description: True if the file name is valid; otherwise, false.
    content.vb: Function IsValidFileName(fileName As String) As Boolean
  overload: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName*
  nameWithType.vb: IFileValidator.IsValidFileName(String)
  fullName.vb: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName(String)
  name.vb: IsValidFileName(String)
- uid: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize(System.Int64,System.Int64)
  commentId: M:AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize(System.Int64,System.Int64)
  id: IsValidFileSize(System.Int64,System.Int64)
  parent: AdvanceFileUpload.Application.Validators.IFileValidator
  langs:
  - csharp
  - vb
  name: IsValidFileSize(long, long)
  nameWithType: IFileValidator.IsValidFileSize(long, long)
  fullName: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize(long, long)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IFileValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IsValidFileSize
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IFileValidator.cs
    startLine: 21
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Validates the file size.
  example: []
  syntax:
    content: bool IsValidFileSize(long fileSize, long maxFileSize)
    parameters:
    - id: fileSize
      type: System.Int64
      description: The size of the file to validate.
    - id: maxFileSize
      type: System.Int64
      description: The maximum allowed size of the file.
    return:
      type: System.Boolean
      description: True if the file size is valid; otherwise, false.
    content.vb: Function IsValidFileSize(fileSize As Long, maxFileSize As Long) As Boolean
  overload: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize*
  nameWithType.vb: IFileValidator.IsValidFileSize(Long, Long)
  fullName.vb: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize(Long, Long)
  name.vb: IsValidFileSize(Long, Long)
- uid: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension(System.String,System.String[])
  commentId: M:AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension(System.String,System.String[])
  id: IsValidFileExtension(System.String,System.String[])
  parent: AdvanceFileUpload.Application.Validators.IFileValidator
  langs:
  - csharp
  - vb
  name: IsValidFileExtension(string, string[])
  nameWithType: IFileValidator.IsValidFileExtension(string, string[])
  fullName: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension(string, string[])
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IFileValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IsValidFileExtension
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IFileValidator.cs
    startLine: 29
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Validates the file extension.
  example: []
  syntax:
    content: bool IsValidFileExtension(string fileExtension, string[] allowedExtensions)
    parameters:
    - id: fileExtension
      type: System.String
      description: The extension of the file to validate.
    - id: allowedExtensions
      type: System.String[]
      description: The allowed extensions of the file to validate.
    return:
      type: System.Boolean
      description: True if the file extension is valid; otherwise, false.
    content.vb: Function IsValidFileExtension(fileExtension As String, allowedExtensions As String()) As Boolean
  overload: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension*
  nameWithType.vb: IFileValidator.IsValidFileExtension(String, String())
  fullName.vb: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension(String, String())
  name.vb: IsValidFileExtension(String, String())
references:
- uid: AdvanceFileUpload.Application.Validators
  commentId: N:AdvanceFileUpload.Application.Validators
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.Application.Validators
  nameWithType: AdvanceFileUpload.Application.Validators
  fullName: AdvanceFileUpload.Application.Validators
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Validators
    name: Validators
    href: AdvanceFileUpload.Application.Validators.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Validators
    name: Validators
    href: AdvanceFileUpload.Application.Validators.html
- uid: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName*
  commentId: Overload:AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName
  href: AdvanceFileUpload.Application.Validators.IFileValidator.html#AdvanceFileUpload_Application_Validators_IFileValidator_IsValidFileName_System_String_
  name: IsValidFileName
  nameWithType: IFileValidator.IsValidFileName
  fullName: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize*
  commentId: Overload:AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize
  href: AdvanceFileUpload.Application.Validators.IFileValidator.html#AdvanceFileUpload_Application_Validators_IFileValidator_IsValidFileSize_System_Int64_System_Int64_
  name: IsValidFileSize
  nameWithType: IFileValidator.IsValidFileSize
  fullName: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileSize
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension*
  commentId: Overload:AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension
  href: AdvanceFileUpload.Application.Validators.IFileValidator.html#AdvanceFileUpload_Application_Validators_IFileValidator_IsValidFileExtension_System_String_System_String___
  name: IsValidFileExtension
  nameWithType: IFileValidator.IsValidFileExtension
  fullName: AdvanceFileUpload.Application.Validators.IFileValidator.IsValidFileExtension
- uid: System.String[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string[]
  nameWithType: string[]
  fullName: string[]
  nameWithType.vb: String()
  fullName.vb: String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: (
  - name: )
