### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.Application.Validators.IChunkValidator
  commentId: T:AdvanceFileUpload.Application.Validators.IChunkValidator
  id: IChunkValidator
  parent: AdvanceFileUpload.Application.Validators
  children:
  - AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData(System.Byte[],System.Int64)
  - AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex(System.Int32)
  - AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize(System.Int64,System.Int64)
  langs:
  - csharp
  - vb
  name: IChunkValidator
  nameWithType: IChunkValidator
  fullName: AdvanceFileUpload.Application.Validators.IChunkValidator
  type: Interface
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IChunkValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IChunkValidator
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IChunkValidator.cs
    startLine: 6
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Interface for validating file chunks.
  example: []
  syntax:
    content: public interface IChunkValidator
    content.vb: Public Interface IChunkValidator
- uid: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex(System.Int32)
  commentId: M:AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex(System.Int32)
  id: IsValidChunkIndex(System.Int32)
  parent: AdvanceFileUpload.Application.Validators.IChunkValidator
  langs:
  - csharp
  - vb
  name: IsValidChunkIndex(int)
  nameWithType: IChunkValidator.IsValidChunkIndex(int)
  fullName: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex(int)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IChunkValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IsValidChunkIndex
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IChunkValidator.cs
    startLine: 13
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Validates the chunk index.
  example: []
  syntax:
    content: bool IsValidChunkIndex(int chunkIndex)
    parameters:
    - id: chunkIndex
      type: System.Int32
      description: The index of the chunk to validate.
    return:
      type: System.Boolean
      description: True if the chunk index is valid; otherwise, false.
    content.vb: Function IsValidChunkIndex(chunkIndex As Integer) As Boolean
  overload: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex*
  nameWithType.vb: IChunkValidator.IsValidChunkIndex(Integer)
  fullName.vb: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex(Integer)
  name.vb: IsValidChunkIndex(Integer)
- uid: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData(System.Byte[],System.Int64)
  commentId: M:AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData(System.Byte[],System.Int64)
  id: IsValidChunkData(System.Byte[],System.Int64)
  parent: AdvanceFileUpload.Application.Validators.IChunkValidator
  langs:
  - csharp
  - vb
  name: IsValidChunkData(byte[], long)
  nameWithType: IChunkValidator.IsValidChunkData(byte[], long)
  fullName: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData(byte[], long)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IChunkValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IsValidChunkData
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IChunkValidator.cs
    startLine: 21
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Validates the chunk data.
  example: []
  syntax:
    content: bool IsValidChunkData(byte[] chunkData, long MaxChunkSize)
    parameters:
    - id: chunkData
      type: System.Byte[]
      description: The data of the chunk to validate.
    - id: MaxChunkSize
      type: System.Int64
      description: The maximum size of the chunk.
    return:
      type: System.Boolean
      description: True if the chunk data is valid; otherwise, false.
    content.vb: Function IsValidChunkData(chunkData As Byte(), MaxChunkSize As Long) As Boolean
  overload: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData*
  nameWithType.vb: IChunkValidator.IsValidChunkData(Byte(), Long)
  fullName.vb: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData(Byte(), Long)
  name.vb: IsValidChunkData(Byte(), Long)
- uid: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize(System.Int64,System.Int64)
  commentId: M:AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize(System.Int64,System.Int64)
  id: IsValidChunkSize(System.Int64,System.Int64)
  parent: AdvanceFileUpload.Application.Validators.IChunkValidator
  langs:
  - csharp
  - vb
  name: IsValidChunkSize(long, long)
  nameWithType: IChunkValidator.IsValidChunkSize(long, long)
  fullName: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize(long, long)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IChunkValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IsValidChunkSize
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/Validators/IChunkValidator.cs
    startLine: 29
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Validators
  summary: Validates the size of the chunk.
  example: []
  syntax:
    content: bool IsValidChunkSize(long chunkSize, long maxChunkSize)
    parameters:
    - id: chunkSize
      type: System.Int64
      description: The size of the chunk to validate.
    - id: maxChunkSize
      type: System.Int64
      description: The maximum allowed size of the chunk.
    return:
      type: System.Boolean
      description: True if the chunk size is valid; otherwise, false.
    content.vb: Function IsValidChunkSize(chunkSize As Long, maxChunkSize As Long) As Boolean
  overload: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize*
  nameWithType.vb: IChunkValidator.IsValidChunkSize(Long, Long)
  fullName.vb: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize(Long, Long)
  name.vb: IsValidChunkSize(Long, Long)
references:
- uid: AdvanceFileUpload.Application.Validators
  commentId: N:AdvanceFileUpload.Application.Validators
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.Application.Validators
  nameWithType: AdvanceFileUpload.Application.Validators
  fullName: AdvanceFileUpload.Application.Validators
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Validators
    name: Validators
    href: AdvanceFileUpload.Application.Validators.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Validators
    name: Validators
    href: AdvanceFileUpload.Application.Validators.html
- uid: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex*
  commentId: Overload:AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex
  href: AdvanceFileUpload.Application.Validators.IChunkValidator.html#AdvanceFileUpload_Application_Validators_IChunkValidator_IsValidChunkIndex_System_Int32_
  name: IsValidChunkIndex
  nameWithType: IChunkValidator.IsValidChunkIndex
  fullName: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkIndex
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData*
  commentId: Overload:AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData
  href: AdvanceFileUpload.Application.Validators.IChunkValidator.html#AdvanceFileUpload_Application_Validators_IChunkValidator_IsValidChunkData_System_Byte___System_Int64_
  name: IsValidChunkData
  nameWithType: IChunkValidator.IsValidChunkData
  fullName: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkData
- uid: System.Byte[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte[]
  nameWithType: byte[]
  fullName: byte[]
  nameWithType.vb: Byte()
  fullName.vb: Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: (
  - name: )
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize*
  commentId: Overload:AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize
  href: AdvanceFileUpload.Application.Validators.IChunkValidator.html#AdvanceFileUpload_Application_Validators_IChunkValidator_IsValidChunkSize_System_Int64_System_Int64_
  name: IsValidChunkSize
  nameWithType: IChunkValidator.IsValidChunkSize
  fullName: AdvanceFileUpload.Application.Validators.IChunkValidator.IsValidChunkSize
