### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.Application.Shared
  commentId: N:AdvanceFileUpload.Application.Shared
  id: AdvanceFileUpload.Application.Shared
  children:
  - AdvanceFileUpload.Application.Shared.RouteTemplates
  langs:
  - csharp
  - vb
  name: AdvanceFileUpload.Application.Shared
  nameWithType: AdvanceFileUpload.Application.Shared
  fullName: AdvanceFileUpload.Application.Shared
  type: Namespace
  assemblies:
  - AdvanceFileUpload.Application.Shared
references:
- uid: AdvanceFileUpload.Application.Shared.RouteTemplates
  commentId: T:AdvanceFileUpload.Application.Shared.RouteTemplates
  href: AdvanceFileUpload.Application.Shared.RouteTemplates.html
  name: RouteTemplates
  nameWithType: RouteTemplates
  fullName: AdvanceFileUpload.Application.Shared.RouteTemplates
