### YamlMime:ManagedReference
items:
- uid: AdvanceFileUpload.Application.Shared.IFileValidator
  commentId: T:AdvanceFileUpload.Application.Shared.IFileValidator
  id: IFileValidator
  parent: AdvanceFileUpload.Application.Shared
  children:
  - AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension(System.String,System.String[])
  - AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName(System.String)
  - AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize(System.Int64,System.Int64)
  langs:
  - csharp
  - vb
  name: IFileValidator
  nameWithType: IFileValidator
  fullName: AdvanceFileUpload.Application.Shared.IFileValidator
  type: Interface
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IFileValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: IFileValidator
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IFileValidator.cs
    startLine: 6
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Interface for validating files.
  example: []
  syntax:
    content: public interface IFileValidator
    content.vb: Public Interface IFileValidator
- uid: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName(System.String)
  commentId: M:AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName(System.String)
  id: ValidateFileName(System.String)
  parent: AdvanceFileUpload.Application.Shared.IFileValidator
  langs:
  - csharp
  - vb
  name: ValidateFileName(string)
  nameWithType: IFileValidator.ValidateFileName(string)
  fullName: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName(string)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IFileValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: ValidateFileName
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IFileValidator.cs
    startLine: 13
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Validates the file name.
  example: []
  syntax:
    content: bool ValidateFileName(string fileName)
    parameters:
    - id: fileName
      type: System.String
      description: The name of the file to validate.
    return:
      type: System.Boolean
      description: True if the file name is valid; otherwise, false.
    content.vb: Function ValidateFileName(fileName As String) As Boolean
  overload: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName*
  nameWithType.vb: IFileValidator.ValidateFileName(String)
  fullName.vb: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName(String)
  name.vb: ValidateFileName(String)
- uid: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize(System.Int64,System.Int64)
  commentId: M:AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize(System.Int64,System.Int64)
  id: ValidateFileSize(System.Int64,System.Int64)
  parent: AdvanceFileUpload.Application.Shared.IFileValidator
  langs:
  - csharp
  - vb
  name: ValidateFileSize(long, long)
  nameWithType: IFileValidator.ValidateFileSize(long, long)
  fullName: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize(long, long)
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IFileValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: ValidateFileSize
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IFileValidator.cs
    startLine: 21
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Validates the file size.
  example: []
  syntax:
    content: bool ValidateFileSize(long fileSize, long maxFileSize)
    parameters:
    - id: fileSize
      type: System.Int64
      description: The size of the file to validate.
    - id: maxFileSize
      type: System.Int64
      description: The maximum allowed size of the file.
    return:
      type: System.Boolean
      description: True if the file size is valid; otherwise, false.
    content.vb: Function ValidateFileSize(fileSize As Long, maxFileSize As Long) As Boolean
  overload: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize*
  nameWithType.vb: IFileValidator.ValidateFileSize(Long, Long)
  fullName.vb: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize(Long, Long)
  name.vb: ValidateFileSize(Long, Long)
- uid: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension(System.String,System.String[])
  commentId: M:AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension(System.String,System.String[])
  id: ValidateFileExtension(System.String,System.String[])
  parent: AdvanceFileUpload.Application.Shared.IFileValidator
  langs:
  - csharp
  - vb
  name: ValidateFileExtension(string, string[])
  nameWithType: IFileValidator.ValidateFileExtension(string, string[])
  fullName: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension(string, string[])
  type: Method
  source:
    remote:
      path: src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IFileValidator.cs
      branch: main
      repo: https://github.com/mohanad-cs/AdvanceFileUpload-.git
    id: ValidateFileExtension
    path: ../src/AdvanceFileUpload/AdvanceFileUpload.Application.Shared/IFileValidator.cs
    startLine: 29
  assemblies:
  - AdvanceFileUpload.Application.Shared
  namespace: AdvanceFileUpload.Application.Shared
  summary: Validates the file extension.
  example: []
  syntax:
    content: bool ValidateFileExtension(string fileExtension, string[] allowedExtensions)
    parameters:
    - id: fileExtension
      type: System.String
      description: The extension of the file to validate.
    - id: allowedExtensions
      type: System.String[]
      description: The allowed extensions of the file to validate.
    return:
      type: System.Boolean
      description: True if the file extension is valid; otherwise, false.
    content.vb: Function ValidateFileExtension(fileExtension As String, allowedExtensions As String()) As Boolean
  overload: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension*
  nameWithType.vb: IFileValidator.ValidateFileExtension(String, String())
  fullName.vb: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension(String, String())
  name.vb: ValidateFileExtension(String, String())
references:
- uid: AdvanceFileUpload.Application.Shared
  commentId: N:AdvanceFileUpload.Application.Shared
  href: AdvanceFileUpload.html
  name: AdvanceFileUpload.Application.Shared
  nameWithType: AdvanceFileUpload.Application.Shared
  fullName: AdvanceFileUpload.Application.Shared
  spec.csharp:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Shared
    name: Shared
    href: AdvanceFileUpload.Application.Shared.html
  spec.vb:
  - uid: AdvanceFileUpload
    name: AdvanceFileUpload
    href: AdvanceFileUpload.html
  - name: .
  - uid: AdvanceFileUpload.Application
    name: Application
    href: AdvanceFileUpload.Application.html
  - name: .
  - uid: AdvanceFileUpload.Application.Shared
    name: Shared
    href: AdvanceFileUpload.Application.Shared.html
- uid: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName*
  commentId: Overload:AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName
  href: AdvanceFileUpload.Application.Shared.IFileValidator.html#AdvanceFileUpload_Application_Shared_IFileValidator_ValidateFileName_System_String_
  name: ValidateFileName
  nameWithType: IFileValidator.ValidateFileName
  fullName: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize*
  commentId: Overload:AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize
  href: AdvanceFileUpload.Application.Shared.IFileValidator.html#AdvanceFileUpload_Application_Shared_IFileValidator_ValidateFileSize_System_Int64_System_Int64_
  name: ValidateFileSize
  nameWithType: IFileValidator.ValidateFileSize
  fullName: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileSize
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension*
  commentId: Overload:AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension
  href: AdvanceFileUpload.Application.Shared.IFileValidator.html#AdvanceFileUpload_Application_Shared_IFileValidator_ValidateFileExtension_System_String_System_String___
  name: ValidateFileExtension
  nameWithType: IFileValidator.ValidateFileExtension
  fullName: AdvanceFileUpload.Application.Shared.IFileValidator.ValidateFileExtension
- uid: System.String[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string[]
  nameWithType: string[]
  fullName: string[]
  nameWithType.vb: String()
  fullName.vb: String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: (
  - name: )
